src/Entity/User.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Util\HideEmail;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AcmeAssert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user_list")
 * @UniqueEntity(
 *     fields={"email", "phone"}
 * )
 */
class User implements UserInterface, \Serializable
{

    private const roleHierarchy =
        [
            'ROLE_ADMIN' => 'Администратор',
            'ROLE_USER' => 'Read-only',
            'ROLE_INACTIVE' => 'Неподтвержденный пользователь'
        ];
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string")
     * @Assert\Length(
     *     max=100,
     *     min=3,
     *     minMessage="Указано слишком короткое имя",
     *     maxMessage="Указано слишком длинное имя")
     */
    private $fullName;

    /**
     * @var string
     * @ORM\Column(type="string", unique=true)
     * @Assert\Email(
     *     message = "Неправильно указан E-mail")
     */
    private $email;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string
     * @ORM\Column(type="string", unique=true)
     * @AcmeAssert\IsPhone
     */
    private $phone;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $company;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var array
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $confirmToken;

    /**
     * @var string
     * @Assert\Blank()
     */
    private $addressCustom;

    private $plainPassword;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Dialog", mappedBy="user", cascade={"persist", "remove"})
     */
    private $dialog;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="owner")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserRequest", mappedBy="user")
     */
    private $userRequests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="owner")
     */
    private $links;


    public function __construct()
    {
        $this->roles[] = 'ROLE_INACTIVE';
        $this->messages = new ArrayCollection();
        $this->userRequests = new ArrayCollection();
        $this->links = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function getPrivateEmail(): ?string
    {
        return HideEmail::hide($this->email);
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getConfirmToken(): ?string
    {
        return $this->confirmToken;
    }

    public function setConfirmToken($confirmToken): self
    {
        $this->confirmToken = $confirmToken;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;

        if (empty($roles)) {
            $roles[] = 'ROLE_INACTIVE';
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    public function getHighestRoleText(): ?string
    {
        foreach ($this->roles as $role)
        {
            if (in_array($role, $this->roles))
            {
                return self::roleHierarchy[$role];
            }
        }
        return null;
    }
    public function getHighestRole(): ?string
    {
        foreach ($this->roles as $role)
        {
            if (in_array($role, $this->roles))
            {
                return $role;
            }
        }
        return null;
    }

    public function serialize(): string
    {
        return serialize([$this->id, $this->email, $this->password]);
    }

    public function unserialize($serialized): void
    {
        [$this->id, $this->email, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getDialog(): ?Dialog
    {
        return $this->dialog;
    }

    public function setDialog(?Dialog $dialog): self
    {
        $this->dialog = $dialog;

        // set (or unset) the owning side of the relation if necessary
        $newUser = $dialog === null ? null : $this;
        if ($newUser !== $dialog->getUser()) {
            $dialog->setUser($newUser);
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setOwner($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getOwner() === $this) {
                $message->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserRequest[]
     */
    public function getUserRequests(): Collection
    {
        return $this->userRequests;
    }

    public function addUserRequest(UserRequest $userRequest): self
    {
        if (!$this->userRequests->contains($userRequest)) {
            $this->userRequests[] = $userRequest;
            $userRequest->setUser($this);
        }

        return $this;
    }

    public function removeUserRequest(UserRequest $userRequest): self
    {
        if ($this->userRequests->contains($userRequest)) {
            $this->userRequests->removeElement($userRequest);
            // set the owning side to null (unless already changed)
            if ($userRequest->getUser() === $this) {
                $userRequest->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Link[]
     */
    public function getLinks(): Collection
    {
        return $this->links;
    }

    public function addLink(Link $link): self
    {
        if (!$this->links->contains($link)) {
            $this->links[] = $link;
            $link->setOwner($this);
        }

        return $this;
    }

    public function removeLink(Link $link): self
    {
        if ($this->links->contains($link)) {
            $this->links->removeElement($link);
            // set the owning side to null (unless already changed)
            if ($link->getOwner() === $this) {
                $link->setOwner(null);
            }
        }

        return $this;
    }

    public function getAddressCustom(): ?string
    {
        return $this->addressCustom;
    }

    public function setAddressCustom(string $address): self
    {
        $this->addressCustom = $address;

        return $this;
    }

}

templates/views/admin/dialogs.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="dialogs">
        <div class="container">
            <div class="row">
                <div class="col-lg-{{ navWidth }}">
                    {% include "views/components/navbar.html.twig" %}
                </div>
                <div class="col-lg-{{ contentWidth }} dialogs-inner">
                    {% if dialogs is not empty %}
                        <h2>Диалоги:</h2>
                        {% for dialog in dialogs %}
                            <div class="dialogs-inner-item">
                                <p><a href="{{ path('profile', {id: dialog.user.id}) }}">{{ dialog.user.email }}</a></p>
                                <p>{{ dialog.user.fullname }}</p>
                                <p><a href="{{ path('adminDialog', {id: dialog.user.id}) }}">Перейти к диалогу</a></p>
                                {#<p><a href="{{ path('deleteDialog', {id: dialog.id}) }}">Удалить диалог</a></p>#}
                            </div>
                        {% endfor %}
                    {% else %}
                        <h2>Пока нет диалогов. <a href="{{ path('profiles') }}">Выберите пользователя</a>, чтобы начать диалог</h2>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/views/admin/profile.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="profile">
        <div class="container">
            <div class="row">
                <div class="col-lg-{{ navWidth }}">
                    {% include "views/components/navbar.html.twig" %}
                </div>
                <div class="col-lg-{{ contentWidth }}">
                    <div class="profile-holder">
                        <h2><span>Профиль:</span> {{ user.email }}</h2>
                        <p><span>ФИО:</span> {{ user.fullname }}</p>
                        <p><span>Компания:</span> {{ user.company }}</p>
                        <p><span>Номер телефона:</span> {{ user.phone }}</p>
                        <p><a href="{{ path('adminDialog', {id: user.id}) }}">Перейти к диалогу с пользователем</a></p>
                        {% if user.highestRole == 'ROLE_INACTIVE' %}
                            <h3>Неподтвержденный пользователь</h3>
                            <p><a href="{{ path('confirmUser', {id: user.id}) }}">Подтвердить</a></p>
                            <p><a href="{{ path('denyUser', {id: user.id}) }}">Отклонить</a></p>
                        {% elseif user.highestRole == 'ROLE_DENIED' %}
                            <h3>Заблокированный пользователь</h3>
                            <p><a href="{{ path('confirmUser', {id: user.id}) }}">Восстановить пользователя</a></p>
                            <p><a href="{{ path('deleteUser', {id: user.id}) }}">Удалить пользователя</a></p>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('denyUser', {id: user.id}) }}">Заблокировать пользователя</a>
                        {% endif %}
                        {% if user.userRequests is not empty %}
                            <h2>Пользовательские заявки:</h2>
                            {% for request in user.userRequests  %}
                                <div class="profile-holder-requests">
                                    <p><a href="{{ path('adminUserRequest', {id: request.id}) }}">Заявка №{{ request.id }} на
                                            объект "{{ request.objectName }}"</a></p>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/views/admin/profiles.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="admin-index">
        <div class="container">
            <div class="row">
                <div class="col-lg-{{ navWidth }}">
                    {% include "views/components/navbar.html.twig" %}
                </div>
                <div class="col-lg-{{ contentWidth }}">
                    <div class="admin-index-active">
                        <h2>Активные пользователи:</h2>
                        {% if userGroups['activeUsers'] %}
                            {% for item in userGroups['activeUsers'] %}
                                <div class="admin-index-active-item admin-index-item">
                                    <p><span>Пользователь:</span><a href="{{ path('adminProfile', {id: item.id}) }}">{{ item.email }}</a> </p>
                                    <p><span>ФИО:</span> {{ item.fullname }}</p>
                                    <p><span>Компания:</span> {{ item.company }}</p>
                                    <p><span>Номер телефона:</span> {{ item.phone }}</p>
                                    <p><a href="{{ path('adminDialog', {id: item.id}) }}">Написать сообщение</a></p>
                                    <p><a href="{{ path('denyUser', {id: item.id}) }}">Заблокировать пользователя</a></p>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="admin-index-active-empty">
                                <p>Нет активных пользователей</p>
                            </div>
                        {% endif %}
                    </div>
                    <div class="admin-index-denied">
                        <h2>Отклоненные пользователи:</h2>
                        {% if userGroups['deniedUsers']  %}
                            {% for item in userGroups['deniedUsers'] %}
                                <div class="admin-index-active-item admin-index-item">
                                    <p><span>ФИО:</span> {{ item.fullname }}</p>
                                    <p><span>Эл. почта:</span>{{ item.email }}</p>
                                    <p><span>Компания:</span> {{ item.company }}</p>
                                    <p><span>Номер телефона:</span> {{ item.phone }}</p>
                                    <p><a href="{{ path('confirmUser', {id: item.id}) }}">Восстановить пользователя</a></p>
                                    <p><a href="{{ path('deleteUser', {id: item.id}) }}">Удалить пользователя</a></p>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="admin-index-active-empty">
                                <p>Нет отклоненных пользователейы</p>
                            </div>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

templates/views/admin/requests.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="dialogs">
        <div class="container">
            <div class="row">
                <div class="col-lg-{{ navWidth }}">
                    {% include "views/components/navbar.html.twig" %}
                </div>
                <div class="col-lg-{{ contentWidth }} dialogs-inner">
                    {% if requests is not empty %}

                        <h2>Заявки по статусу: "{{ requests[0].status.content }}"</h2>

                        <table>
                            <tbody>
                            <tr>
                                <th class="col-lg-4" style="text-align: center;">
                                    <p>Имя:</p>
                                </th>
                                <th class="col-lg-2" style="text-align: center;">
                                    <p>Обновлено:</p>
                                </th>
                                <th class="col-lg-2" style="text-align: center;">
                                    <p>Создано:</p>
                                </th>
                                <th class="col-lg-4" style="text-align: center;">
                                    <p>Статус:</p>
                                </th>
                            </tr>
                        {% for request in requests %}
                            <tr>
                                <td style="text-align: center;">
                                    <a href="{{ path('userRequest', {id: request.id}) }}">
                                        Объект "{{ request.objectName }}"
                                    </a>
                                </td>
                                <td style="text-align: center;">
                                    <p>{{ request.updatedAt|date("d/m/Y, H:i") }}</p>
                                </td>
                                <td style="text-align: center;">
                                    <p>{{ request.createdAt|date("d/m/Y") }}</p>
                                </td>
                                <td style="text-align: center;">
                                    <p>{{ request.status.content }}</p>
                                </td>

                            </tr>
                        {% endfor %}

                            </tbody>
                        </table>

                    {% else %}
                        <h2>Нет заявок в данной категории</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}